### ISSUE TITLE
Outbound emails do not send, nothing in logs

### ISSUE THREAD

**Issue by JoelFeiner** [bitnami/bitnami-docker-mediawiki#87]
**Description**

I have set up the docker compose file to include the following environment variables:
```
     - 'MEDIAWIKI_SMTP_HOST=tls://smtp.office365.com'
     - 'MEDIAWIKI_SMTP_PORT=587'
     - 'MEDIAWIKI_SMTP_USER=user@example.com'
     - 'MEDIAWIKI_SMTP_PASSWORD=somepassword'
```

However, in the logs, whenever I get to a point where it would send an email, I see this error message:
```
sh: 1: /usr/sbin/sendmail: not found
172.27.90.121 - - [12/Jan/2021:19:06:08 +0000] "POST /wiki/Special:ConfirmEmail HTTP/1.1" 200 14559
```

So it seems like the image is missing sendmail? Either that or there is some other misconfiguration. I'm not sure, however, what that might be.

I have verified that it is possible to send emails (and receive from other accounts) using the address we created.

**Version**

- Output of `docker version`:

```
Docker version 19.03.13, build 4484c46d9d
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 19
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.4.238-1.el7.elrepo.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.858GiB
 Name: lm.intranet-nyj01.warpwire.net
 ID: 4BLB:QRAU:K3ES:YH4X:URJ3:6EOM:SAE5:BRQY:VE6J:JA2P:5RFS:4J2M
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Output of `docker image ls`:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
bitnami/mediawiki   1                   eb5f0b3c9241        11 hours ago        1.12GB
```

And according to `docker container inspect`, the image is: `"Image": "sha256:eb5f0b3c9241260cefbe0f16d6920b64b3836dc386d44c79456da8441f03e64f"`

**Comment by miguelaeh** [comment]
Hi @JoelFeiner ,
There is an error in the README.md, please remove the `tls://` part from the host. Also, you need to add the `MEDIAWIKI_SMTP_HOST_ID`.
We have already addressed the README issue and it will be published soon.
Reagards.

**Comment by JoelFeiner** [comment]
@miguelaeh I have made those changes, but it still fails to send. When I use the Confirm email address page, I get this error:
```
Mailer returned: Unknown error in PHP's mail() function. 
```

Of course, there's not much I can do with that since it doesn't tell me what the problem is.

For what it's worth, here is the new config via the environment in the container:
```
MEDIAWIKI_SMTP_PORT=587
MEDIAWIKI_SMTP_HOST=smtp.office365.com
MEDIAWIKI_SMTP_PASSWORD=<redacted>
MEDIAWIKI_SMTP_USER=wiki@<domain>
MEDIAWIKI_SMTP_HOST_ID=<domain>
```

I'm still not entirely clear on what HOST_ID is supposed to be, but I assume it is the second level domain, e.g. example.com if my wiki was at wiki.example.com. If I'm wrong, please let me know.

**Comment by miguelaeh** [comment]
Hi @JoelFeiner ,

About the HOST_ID:

> MEDIAWIKI_SMTP_HOST_ID: SMTP host ID. It is a MediaWiki-specific setting used to build the Message-ID email header. If not provided, it will default to the value of MEDIAWIKI_SMTP_HOST.

We have just tested this on our side and seems to be working. Could you try fetching the latest image and deploying the docker-compose in other folder from scratch? 
Also, sometimes the issues are related to the SMTP provider used, have you tried with a different one than office365?

**Comment by JoelFeiner** [comment]
> Hi @JoelFeiner ,
> 
> About the HOST_ID:
> 
> > MEDIAWIKI_SMTP_HOST_ID: SMTP host ID. It is a MediaWiki-specific setting used to build the Message-ID email header. If not provided, it will default to the value of MEDIAWIKI_SMTP_HOST.

Unfortunately, this does not explain to me what it actually ought to be set to in various cases. In examples I've seen, it is set to the domain of the wiki. When using `$wgSMTP`, I have set `IDHost` to our wiki domain and it seems to work fine.

> We have just tested this on our side and seems to be working. Could you try fetching the latest image and deploying the docker-compose in other folder from scratch?

Is there a new build since yesterday? I have my compose set up to always fetch the latest.

> Also, sometimes the issues are related to the SMTP provider used, have you tried with a different one than office365?

We will ultimately need to use Office365. As I noted above, using the `$wgSMTP` section explicitly in `LocalSettings.php`, it works fine. It's only when it's only done via environment variables that it fails to work.

How do the environment variables actually turn into SMTP configuration in the Docker container? I can't find any code in this repository that handles that, so I don't understand the process. Is it possible that it only works when it first generates LocalSettings.php and not if the file already exists in the mapped data directory? If so, that would explain why it never set anything up.

**Comment by JoelFeiner** [comment]
I see what the problem is. If there is already a LocalSettings.php file, the Docker process will *not* add settings to the file. It only does that if the file does not already exist. However, if the file does not already exist, I just get these messages:
```
mediawiki 16:00:51.23 Welcome to the Bitnami mediawiki container
mediawiki 16:00:51.23 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mediawiki
mediawiki 16:00:51.24 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mediawiki/issues
mediawiki 16:00:51.24 
mediawiki 16:00:51.24 INFO  ==> ** Starting MediaWiki setup **
mediawiki 16:00:51.27 DEBUG ==> Validating settings in APACHE_* environment variables
mediawiki 16:00:51.29 INFO  ==> Configuring PHP options
mediawiki 16:00:51.31 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
mediawiki 16:00:51.34 DEBUG ==> Validating settings in MEDIAWIKI_* environment variables...
mediawiki 16:00:51.41 INFO  ==> Restoring persisted MediaWiki installation
mediawiki 16:00:51.46 INFO  ==> Trying to connect to the database server
mediawiki 16:00:51.47 DEBUG ==> Getting $wgDBserver from MediaWiki configuration
mediawiki 16:00:51.47 DEBUG ==> ^\s*(//\s*)?\$wgDBserver\s*=([^;]+);
grep: /opt/bitnami/mediawiki/LocalSettings.php: No such file or directory
```

The only way around that is to completely delete the shared volume data so that it gets scaffolded when the container starts. It'd be great if it could create the missing LocalSettings.php file even if the other files exist. Is that something that can be done? I think that is one of the two things that would solve this issue. The other is to have settings applied to an existing LocalSettings.php file.

**Comment by miguelaeh** [comment]
Hi @JoelFeiner ,
The image only generates the configuration when there is not a volume mounted or the volume is empty. When you see the following meesage into the log the configuration will be the stored one, not the new provided one:
```
Restoring persisted MediaWiki installation
```

If you are working in a testing scenario try the following:

- In case you use docker volumes:

```console
docker-compose down -v
docker-compose up
```

- In case you are mapping local volumes:
 1. Either empty the local folder or map a different one in the docker-compose
 2.
```console
docker-compose down
docker-compose up
```

If you can't manipulate the current installation because it is beign used as production, cretate a new folder with the docker-compose and since there are not an already initialized volume by default it should work

**Comment by JoelFeiner** [comment]
@miguelaeh 

I understand what it does, but I don't understand why. Is there a reason the Docker script can't create the file if it doesn't exist, even if the volume itself already exists? I also don't understand why it can't update the file if the configuration via environment variables changes when rerunning Docker compose. Can that change be made? This would make it considerably easier to upgrade or change settings.

That would have solved this issue. The reason the settings didn't work is because I already had a LocalSettings.php and so the Docker script did not change anything in the configuration.

**Comment by miguelaeh** [comment]
Hi @JoelFeiner ,
It is because of the way we build the images. By default, if the volume is already initialized it means that the users are running the application with their custom settings so in that case we don't want to override the user custom configuration in the initialization.

> Can that change be made? This would make it considerably easier to upgrade or change settings.

So attending to the described above, we don't plan to make those changes.
